apiVersion: v1
kind: Service
metadata:
  name: kublab-service
  namespace: kublab
spec:
  selector:
    app: lab
  ports:
    - name: application
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP